### ISSUE TITLE
[Models] Create User Model

### ISSUE THREAD

**Issue by casmeyu** [casmeyu/book_store#1]
Create User model with basic attributes using **SQLAlchemy**
User should have at least a Role associated with it (vendor, admin, etc) this is an N:N relationship with the Roles entity
**Initial idea for User model**
**User {**
....**id** int auto_increment PK
....**username** string unique not null
....**password** string not null
....**created_at** datetime not null
....**updated_at** datetime not null
....**deleted_at** datetime not null
....**roles** many2many relationship with **Roles entity**
**}**

**Comment by casmeyu** [comment]
Create init function for user
Create an ENVIRONMENT VARIABLE in the .env file called PASSWORD_REGEX containing a regular expression containing letters an numbers.

**Comment by casmeyu** [comment]
@EricAltez 
For the basic Queries for the entities
https://docs.sqlalchemy.org/en/20/orm/queryguide/select.html#selecting-orm-entities

**Comment by EricAltez** [comment]
Done

**Comment by EricAltez** [comment]
asegurarse que el nombre del usuario sea unico

**Comment by casmeyu** [comment]
@EricAltez Esta tarea esta completada al final?
